spring.application.name=Spring-boot-first-practice-project-01

spring.datasource.url = jdbc:mysql://localhost:3306/expensetrackerDB
spring.datasource.username= root
spring.datasource.password= root

spring.jpa.hibernate.ddl-auto= update

spring.jpa.show-sql= true
#server.servlet.context-path= /api/v1

server.port = 9090
